version: '3.7'

services:
  prometheus:
    #image: prom/prometheus:latest
    image: registry.cn-shenzhen.aliyuncs.com/yyf-compose/prometheus:v7-20201105
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
    networks:
      - mynet

  node-exporter:
    #image: prom/node-exporter:latest
    image: registry.cn-shenzhen.aliyuncs.com/yyf-compose/node-exporter:v7-20201105
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    networks:
      - mynet


  cadvisor:
    #image: google/cadvisor:latest
    image: registry.cn-shenzhen.aliyuncs.com/yyf-compose/cadvisor:v7-20201105
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - mynet


  grafana:
    #image: grafana/grafana:latest
    image: registry.cn-shenzhen.aliyuncs.com/yyf-compose/grafana:v7-20201105
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    user: '0'
    #volumes:
    #  - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    #  - ./grafana/data:/var/lib/grafana
    #  - ./data/grafana-data:/usr/share/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://192.168.5.45:3000
    networks:
      - mynet

#  alertmanager:
#    image: prom/alertmanager:latest
#    container_name: alertmanager
#    hostname: alertmanager
#    restart: always
#    volumes:
#        - ./alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
#    ports:
#        - "9093:9093"
#    networks:
#      - mynet

networks:
  mynet:
    driver: bridge
