global:
  smtp_smarthost: 'smtp.qq.com'　　#163服务器
  smtp_from: '2875541071@qq.com'　　　　　　　　#发邮件的邮箱
  smtp_auth_username: '2875541071@qq.com'　　#发邮件的邮箱用户名，也就是你的邮箱
  smtp_auth_password: 'lqyjhfuqgwqjdgfj'　　　　　　　　#发邮件的邮箱密码
  smtp_require_tls: false　　　　　　　　#不进行tls验证

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: '1575169034@qq.com'
