version: '3'
services:
  master:
    image: mysql:5.7
    container_name: master
    environment:
      MYSQL_ROOT_PASSWORD: '666666'
    #ports:
    #  - "3306:3306"
    privileged: true
    volumes:
      - ./master/etc/my.cnf:/etc/my.cnf
      #- ./master/data:/var/lib/mysql
    restart: always

  slave:
    image: mysql:5.7
    container_name: slave
    environment:
      MYSQL_ROOT_PASSWORD: '666666'
    #ports:
    #  - "3307:3306"
    privileged: true
    volumes:
      - ./slave/etc/my.cnf:/etc/my.cnf
      #- ./slave/data:/var/lib/mysql
    restart: always
